language: scala

stages:
  - test
  - release

jdk:
  - openjdk8

scala:
  - 2.11.12
  - 2.12.6

script:
  - project/voltdbscala test

jobs:
  include:
    - stage: release
      scala: 2.12.6
      script: project/voltdbscala release

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

before_install:
  - openssl aes-256-cbc -k "$ENC_PASSWORD" -in .secring.gpg.enc -out .secring.gpg -d
  - openssl aes-256-cbc -k "$ENC_PASSWORD" -in .pubring.gpg.enc -out .pubring.gpg -d

notifications:
  email:
    - r-and-d@slack.full360.com

env:
  global:
    # ENC_PASSWORD
    # SONATYPE_USERNAME
    # SONATYPE_PASSWORD
    # SONATYPE_KEY_NAME
    # SONATYPE_KEY_PASSPHRASE
    - secure: owgYtZkhvKxhQxDV71Bhp4YZEVw3gDZ8ClOOr0XBoFGVQ1RdXWPuzipYa2T6Bcg2z94yI03qdFC4c3haFDvx0+64uiUEWLbNfOJmQ/bWfQFzm6lT+qEyNnr3AIXqDnQjKAo3wvUR//o013qV6BRjWMVJGlUNW/goBc82eB5L34kOAsSkv8kXnXDJczvSYNOg7gdIct7Sw8mtk9GJtbdhU3RFmo2rxlAGD23A+z/yxxwYS0KRbP0OFhRGhWWRXnAMjQZ1bAMZwftCSdlV8fi74eOLDTIfBLAXHCO1QxEkuVJxnso/f5ZxXekg4f83IYmIrfrUBlrZKiRMt5pbzwq0erJ1fIfkO6XDeQxYvU1XrWfm9RiGTlqWTQ8o5YsjuCEB3kInSrvvLcJ98ZYVkPPDgdL/sYaQCxn7kWExMVXg4bnkbJTEaE5GMdLQJqjED/DHtddSxJko3BY0+SQxLPVC/KEDcJJZtFfooQhwHLsh8boyUH91ZC+GAjA5q2U3IH/tAKPyVJes7qvTXa4Zc6siRDzB4MQJ3go7lrS+3MI+4RyKsW5tx77ZkglDvtRjH/JoZUbVI1B6lvglqkxrtrQOERtTLGWAxIXv69FzX8LS6wC2re+Qz3WaFna9N08iflJipyv4gn3yxqAPL0RhL4F2OkPGydeTjEPUV4BrqaUMMts=
    - secure: rmUdjfjyawPOqVl7DybvbMHK2kGLzql11QsG0JEefLn0TTHqyMjiyKjqZ5oba9DS6FzMtFQjgo9D7WUOZ3JX04hWY6cOri42tJkEMdsUDexGBHhDAqqLJ8gssCmM6NbQl1y+SmAZqTaLuHirnGU9MHj3b586CmnsZ/LVkAGstXGilznsq540WsbvuvtrD7pZttl8y3nJPrmid/1O83mU13Kka8CPv1pnT/zmuPbBy185TOxXJsofd77gNbj+lxdTbei6qJoRWSptYxKNhdVt1R+y3GJyowFmlI8MbLF3NF6MjVEaHudZZ6Y5xFtxTAnNW3SknoSmbUef2qI58fyMoQXSYxoogf+xqUMFZkPMmnVWEJHVu98tKsVsRTj6koCYZCqLssriN0vRHTqFpWe8LfFqUQrGVV5PKN44hlXuMBeg7qWFsNDUAsK8f0SHgW7gIx3spq6fNqJTznxk4fcaUBHehVWxM5dkLmzwzo3PFc+R6iudNGUayEYHogv9jiEpMPDmFBnjoGBr41DuVY00JEHcOfxoaqzTng0YFoDMv3CQPxhZXtL8RA2ENyOBmabjMW6OfZdOCRYmy4cvt6QLJD6kcP2oPk75+8p22/yrsd6F5/rZ0u2P7MMpS/aZ9c1TT9IVjwWD//aNRAo+EdG7lkhLrCxwwN+8B8mgCTetP7A=
    - secure: lWNbZyqksgJejXraWSVqnBZNrfQ3yMvDynBEZ9OZHvf8mQ1u1eqRPRpQ2FQ4r2zv6/8s24jnXMed0lVaMDI0s3TLChwRJVV8BjAzTytWfN1oJP6n3dcMH58czlZkdttJARyweIneQf4pYFWatY9zJ5kjiU1ww5zYRH0LGccKCHyFSrzvy6HW+2mU40fzdoBGe1xRhU7xCNUT78z/YxpqnmD+2xwEswGhJr1qaLp1z7ZKj4vHQjylylsG+5NAffuznW+haQNPl8uKiMQvMsdFQBunkr3Tci9pvlza0LENCS0BCH4bjyt5JqsNPSzybJlRSX1Q97ARyj/p5vOguD41MGjoRpDggI/AM0GMMOyrRsehxRAs3FBnaQEO0U0IcY9rZ5too3ZD6DrlykMQIo5QHlGmfbvaAXJruRrcTXsx7cS8e7ZOQvkj3BMNkiSdLqimVJR5OaArTFbPSBB8WOp3wSgZQEsVsG07S/dy+E/rvFS6ZSUoKTCcKv57UWqckI2K075qgiHWL5Fx1/4G3AsLWI6vTUZUPi4Ivp0xKINhNjrhskb9p56DRqLJidt4XpNtIkyjMPcbJbXUuBCtbA98KfOSW200nItRa7sjbs+vqQXAqBqnAhXKfk26wK3nsVVPz0JwRt83KECncPvEn+di8DQzYF1MLfCBG1/uEGh1GHI=
    - secure: KwKidsMNuf51EMkOZn5lRCxZx6Pqo+NOwI+rMzRU6fkdaW4LtKMpbPS08EdJrApubE8rwRnyPYqa0e3iS9AtLqZEHOMtfknTTrUMdfTUj9jkWL97PUe3WsUQVYGwA66cqu9tfgK2DznK8Qt3xQFqQNwmJ49RrucPvrsstXUIxAYHGpTFXjrOZnFmQT3HZ5XUWWZ4Li1SGRTD3jhB6a/BErDMjcKtZvRR2wzQ4ylziY2Mnj9eWHFHYySL20gQaGLdUnNb2Jn06Wr1vb4kgA1bJgafBN2wReC/nOhwNGPQl93j4iXQOdavBGvhwNq7QJ3KZXnxfMoHlocCw9Pz262LNbbc/HB6doNEuU2zLuFGb9MbdEAEt7u6LIxLhXzLibiUkWOPkJ7TraW4F8rdj+v4MGGR6m3kaQTLEwFziR+xJMjTVQudmKtj0VkPtNNVXs3v2FOuk2G/8sSGw9tWkaKqsoTJN84CXicbqjsMZArBOZEgx9mMun8QrOcFFeQvMiDMSHOMGNx0SDDYs+4fqvHM4ArA9MATnBMbUQ/yG9zWrCd645Zg68vkB/EDJ1Zv5aO+vpb0H1daEMESPTkj9Micv0sUYB5quyxVXEn8+HCrar0UI5rox0Q87yrNFWRsgier2O0QzTZmSsg26vU9290Fnu8rVv/anYSF2kI12O7o1sk=
    - secure: LElCIp02d8NkQjngyb10Yqnattr45aBZlAUKj6hvJSbxTWxKoVTP6h2e51RjnwwtQjrG4WNmHjafFMxrEov8iHV1OojFkwrKJfN6ZnGEs8T6Pq5eDn93Su9oAGZ2rZvKeLreFaGKbgbttjxnosM16vtyuFm+X9duWHp0tN2y8enc9XS2FznEBOAEiKR+YPHCM4nEyQ8uHelqwarFN/fSVKHoNR6aHY2IT2Bp1MUOL2q8+W8yW281jJo//JApB5KEfzCSgf73++FYE0bR08fwqP3hbBUOLNZZ3U6cIantP8os0ULkMRoroKSNdvT/4wKb8O8nJjW56I+RefWVVG8rZJKei4Z2PmVg+dOGPF5Ef5kbLTQ/IMbyDdM4C5pAg6UBx8pebYZufKGeyDmezwOrKQ7F/9E0j+2azN1fLw3gvyS7ZJA7ixl4JbLoVOZLuKKqMGb1sYuFQT8/wBipYMh3yykjOs334Hi1bFbSPrXZnYUQXW+E4EO2WzSIeaLJINOTnSaTVFlUBshQrrEgOL8+0HLK958FMBsVk4gqKPgNUCBkd1mZvs2cTPm+gctaKrQrTfpiG/Ovki66tGLeErH3tnnvRm3XX1aMthShqIBrKcrys/ALPnTjxIRcs0EvcPhBVTwxbl/6iFb44Wa56/I62UgsjtJ+B0yEBiMMGxAnyJ0=
